# Generated by Django 5.2.1 on 2025-05-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
